[package]
name = "retag"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
audiotags = "0.5.0"
mlua = {version = "0.11.5", features = ["luajit", "anyhow", "vendored", "serde"]}
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_yml = "0.0.12"
